Fix/added release workflow
Contentstack-Solutions/contentstack-cli-content-type pull request #7
Opened 2023-02-02 11:31 UTC by abhinav-from-contentstack

2023-02-07 10:39 UTC, netrajpatel commented
@abhinav-from-contentstack 
The GitHub workflow is failing, can you fix that?

2023-02-09 11:54 UTC, netrajpatel commented
@abhinav-from-contentstack This workflow is failing, please fix this.

2023-02-09 11:59 UTC, netrajpatel requested changes

2023-02-09 11:59 UTC, netrajpatel commented on .github/workflows/release.yml
> +name: Release contentstack-cli-content-type
@abhinav-from-contentstack Github actions are failing

2023-02-09 11:59 UTC, abhinav-from-contentstack commented
@netrajpatel Are you referring to the node.js CI workflow? 

It was added by the author of this repository. It tries to build the package using old versions of node, and then runs the test cases. I've never seen it run successfully yet.

Should I fix this?

2023-02-09 12:00 UTC, netrajpatel commented
> @netrajpatel Are you referring to the node.js CI workflow?
> 
> It was added by the author of this repository. It tries to build the package using old versions of node, and then runs the test cases. I've never seen it run successfully yet.
> 
> Should I fix this?

Yes please fix this as well.

2023-02-16 10:07 UTC, abhinav-from-contentstack commented on .github/workflows/release.yml
> +name: Release contentstack-cli-content-type
I've added a fix @netrajpatel , please have a look.

2023-02-16 10:53 UTC, netrajpatel requested changes
@abhinav-from-contentstack 
Please add a note for the plugin version update

2023-02-16 11:09 UTC, abhinav-from-contentstack commented
@netrajpatel done

2023-02-16 11:38 UTC, netrajpatel approved these changes

2023-07-05 06:33 UTC, aman19K commented
Handled in PR #9

2023-07-05 06:33 UTC, closed without merging